version: '3.8'

services:
  invoiceapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Email__Host=papercut
      - Email__Port=25
      - Email__EnableSsl=false
    depends_on:
      - papercut

  papercut:
    image: jijiechen/papercut:latest
    ports:
      - "25:25"
      - "37408:37408"